# Generated by Django 5.2.6 on 2025-09-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
